services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: listings_db
      POSTGRES_USER: listings_user
      POSTGRES_PASSWORD: listings_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db

volumes:
  postgres_data: 